server:
  address: ":26655"

remote:
  address: "95.31.16.97:26655"

profiles:

  - name: factorio
    game: factorio
    root: C:\Factorio

  - name: minecraft
    game: minecraft
    root: C:\Users\dxo1a\AppData\Roaming\.tlauncher\legacy\Minecraft\game